# Generated by Django 5.2 on 2025-05-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_order_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('denegada', 'Denegada')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Papelería', 'Papelería'), ('Electrónicos', 'Electrónicos'), ('Materiales de Construcción', 'Materiales de Construcción'), ('Herramientas', 'Herramientas')], max_length=30, null=True),
        ),
    ]
